export type PracticeQuestion = {
  id: string; discipline: string; subject: string; topic: string;
  statement: string; options: string[]; answer: number; explanation: string;
  basis: string; source: string; rubric?: string[];
};

export const SOURCES = {
  cf: 'https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm',
  clt: 'https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452.htm',
  cpc: 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm',
  servidor: 'https://www.planalto.gov.br/ccivil_03/leis/l8112cons.htm',
  processo: 'https://www.planalto.gov.br/ccivil_03/leis/l9784.htm',
  lgpd: 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm',
  regimento: 'https://www.trt4.jus.br/portais/trt4/regimento-interno',
  tst: 'https://www.tst.jus.br/livro-de-sumulas-ojs-e-pns',
  cancelamentos: 'https://juslaboris.tst.jus.br/handle/20.500.12178/251919',
};

// Questões autorais. Não são questões da FCC nem reproduções de provas oficiais.
export const PRACTICE_BANK: PracticeQuestion[] = [
  { id:'lp-foro', discipline:'labor-procedure', subject:'Direito Processual do Trabalho', topic:'Competência territorial', statement:'Ana foi contratada em Porto Alegre e sempre trabalhou em Canoas. Sem hipótese excepcional de competência, onde deve ajuizar a reclamação?', options:['Porto Alegre, obrigatoriamente','Canoas, local da prestação dos serviços','Qualquer capital','Brasília','Somente no seu domicílio'], answer:1, explanation:'A regra é o local da prestação dos serviços. O local da contratação não prevalece automaticamente. As exceções dos parágrafos do art. 651 exigem fatos próprios, ausentes no enunciado.', basis:'CLT, art. 651, caput', source:SOURCES.clt, rubric:['Identificar a regra territorial','Aplicar o local de prestação','Explicar por que a contratação não muda a regra neste caso'] },
  { id:'lp-testemunhas', discipline:'labor-procedure', subject:'Direito Processual do Trabalho', topic:'Prova testemunhal', statement:'Em dissídio individual sujeito ao rito sumaríssimo, cada parte pretende ouvir quatro testemunhas. Qual é o limite legal por parte?', options:['Uma','Três','Quatro','Duas','Seis'], answer:3, explanation:'No sumaríssimo, o máximo é duas testemunhas por parte. No ordinário, a regra é três; no inquérito para apuração de falta grave, seis. Não confunda os procedimentos.', basis:'CLT, arts. 821 e 852-H, § 2º', source:SOURCES.clt },
  { id:'lp-preposto', discipline:'labor-procedure', subject:'Direito Processual do Trabalho', topic:'Audiência e representação', statement:'Uma empresa nomeia preposto que não é empregado, mas conhece os fatos. Esse dado, isoladamente, impede a representação?', options:['Sim, sempre','Sim, salvo microempresa','Não; o preposto não precisa ser empregado','Não, porque suas declarações nunca vinculam a empresa','Sim, se a causa superar 40 salários mínimos'], answer:2, explanation:'O § 3º dispensa vínculo de emprego. Permanece a exigência de conhecimento dos fatos; as declarações obrigam o proponente. Dispensa de vínculo não é dispensa de conhecimento.', basis:'CLT, art. 843, §§ 1º e 3º', source:SOURCES.clt, rubric:['Dispensa de vínculo empregatício','Conhecimento dos fatos','Vinculação da empresa às declarações'] },
  { id:'lp-idpj', discipline:'labor-procedure', subject:'Direito Processual do Trabalho', topic:'Incidente de desconsideração', statement:'Na execução trabalhista, o juiz decide o incidente de desconsideração. Qual recurso é cabível, segundo a CLT?', options:['Recurso ordinário em 15 dias','Agravo de petição, independentemente de garantia do juízo','Apelação','Recurso de revista direto, sempre','Nenhum recurso em qualquer fase'], answer:1, explanation:'Na execução cabe agravo de petição sem garantia. Na cognição não cabe recurso imediato; se a decisão for do relator no tribunal, cabe agravo interno. A fase processual define a resposta.', basis:'CLT, art. 855-A, § 1º', source:SOURCES.clt, rubric:['Identificar a fase de execução','Indicar agravo de petição','Dispensar garantia do juízo neste incidente'] },
  { id:'lp-embargos', discipline:'labor-procedure', subject:'Direito Processual do Trabalho', topic:'Recursos', statement:'Uma sentença trabalhista contém omissão. Qual é o prazo ordinário para embargos de declaração?', options:['Oito dias úteis','Quinze dias corridos','Dez dias úteis','Trinta dias','Cinco dias úteis'], answer:4, explanation:'Os embargos de declaração têm prazo de cinco dias. A contagem processual trabalhista é em dias úteis, excluindo o começo e incluindo o vencimento. O prazo de oito dias do recurso ordinário não se aplica.', basis:'CLT, arts. 775 e 897-A', source:SOURCES.clt },
  { id:'lt-experiencia', discipline:'labor-law', subject:'Direito do Trabalho', topic:'Contrato de experiência', statement:'Foi ajustado contrato de experiência de 60 dias, prorrogado uma vez por mais 40. Qual limite foi ultrapassado?', options:['30 dias','60 dias','90 dias','120 dias','Dois anos'], answer:2, explanation:'O contrato de experiência não pode superar 90 dias no total, incluindo prorrogação. Uma única prorrogação não autoriza superar esse teto. O limite geral de dois anos dos contratos a termo não substitui o limite especial.', basis:'CLT, arts. 445, parágrafo único, e 451', source:SOURCES.clt, rubric:['Somar 60 + 40 = 100 dias','Aplicar teto especial de 90 dias','Distinguir número de prorrogações e duração total'] },
  { id:'lt-acordo', discipline:'labor-law', subject:'Direito do Trabalho', topic:'Extinção por acordo', statement:'Empregado e empregador encerram o contrato por acordo do art. 484-A. Qual consequência está correta?', options:['Seguro-desemprego e saque integral','Metade de todas as verbas','Multa de 40% e seguro-desemprego','Aviso indenizado e indenização do FGTS pela metade; saque até 80%, sem seguro-desemprego','Nenhum saque do FGTS'], answer:3, explanation:'Somente o aviso prévio, se indenizado, e a indenização do FGTS são pagos pela metade. As demais verbas são integrais. O saque é limitado a 80%; não há ingresso no seguro-desemprego.', basis:'CLT, art. 484-A', source:SOURCES.clt, rubric:['Separar verbas integrais e verbas pela metade','Indicar limite de saque de 80%','Afastar seguro-desemprego'] },
  { id:'lt-intervalo', discipline:'labor-law', subject:'Direito do Trabalho', topic:'Intervalo intrajornada', statement:'Em contrato atual, sujeito à regra legal de intervalo de uma hora, foram concedidos apenas 40 minutos. Sem norma coletiva aplicável, qual pagamento decorre da supressão?', options:['20 minutos com acréscimo de 50%, de natureza indenizatória','Uma hora inteira de natureza salarial','40 minutos sem adicional','Duas horas com adicional de 100%','Nenhum pagamento'], answer:0, explanation:'Pela redação atual do art. 71, § 4º, paga-se apenas o período suprimido (60 − 40 = 20 minutos), com adicional de 50% e natureza indenizatória. Não aplique automaticamente a disciplina anterior à reforma.', basis:'CLT, art. 71, § 4º', source:SOURCES.clt, rubric:['Calcular 20 minutos suprimidos','Aplicar adicional de 50%','Indicar natureza indenizatória e regime temporal'] },
  { id:'lt-noturno', discipline:'labor-law', subject:'Direito do Trabalho', topic:'Trabalho noturno urbano', statement:'No trabalho urbano, qual combinação corresponde à regra legal da hora noturna?', options:['60 minutos e 10%','52 minutos e 30 segundos e adicional mínimo de 20%','50 minutos e 25%','60 minutos e 30%','45 minutos e 50%'], answer:1, explanation:'A hora noturna urbana é reduzida para 52min30s e recebe adicional de pelo menos 20%. O período legal urbano é das 22h às 5h. Não transplante as regras do trabalho rural.', basis:'CLT, art. 73, caput e §§ 1º e 2º', source:SOURCES.clt },
  { id:'lt-alteracao', discipline:'labor-law', subject:'Direito do Trabalho', topic:'Alteração contratual', statement:'O empregado assina alteração contratual que lhe causa prejuízo direto. O consentimento basta para validar a mudança?', options:['Sim, sempre','Sim, se verbal','Não; exige-se consentimento mútuo e ausência de prejuízo direto ou indireto','Sim, se não houver sindicato','Sim, após 90 dias'], answer:2, explanation:'Os requisitos são cumulativos. O consentimento não sana alteração prejudicial vedada pelo art. 468. Na análise concreta, verifique se existe exceção legal específica; o enunciado não apresenta nenhuma.', basis:'CLT, art. 468, caput', source:SOURCES.clt },
  { id:'cf-tst', discipline:'constitutional', subject:'Direito Constitucional', topic:'Organização da Justiça do Trabalho', statement:'Qual alternativa descreve corretamente a composição e a aprovação dos ministros do TST?', options:['33 ministros; maioria simples do Senado','27 ministros; aprovação pela Câmara','27 ministros; brasileiros de qualquer idade','27 ministros; brasileiros com mais de 35 e menos de 70 anos, aprovados pela maioria absoluta do Senado','Sete ministros; aprovação pelo CNJ'], answer:3, explanation:'A Constituição prevê 27 ministros, brasileiros com mais de 35 e menos de 70 anos, nomeados pelo Presidente da República após aprovação pela maioria absoluta do Senado. As idades são limites estritos.', basis:'CF, art. 111-A', source:SOURCES.cf },
  { id:'cf-casa', discipline:'constitutional', subject:'Direito Constitucional', topic:'Direitos fundamentais', statement:'Existe ordem judicial de ingresso em residência, sem consentimento, sem flagrante, desastre ou necessidade de socorro. Quando a Constituição permite seu cumprimento?', options:['A qualquer hora','Somente durante o dia','Somente à noite','Somente aos domingos','Nunca'], answer:1, explanation:'A determinação judicial permite ingresso durante o dia. Flagrante, desastre e socorro são hipóteses distintas, sem essa limitação constitucional expressa. A ordem judicial, sozinha, não autoriza ingresso noturno.', basis:'CF, art. 5º, XI', source:SOURCES.cf, rubric:['Distinguir ordem judicial das demais exceções','Aplicar exigência de período diurno','Concluir que ordem sozinha não permite ingresso noturno'] },
  { id:'cf-garantia', discipline:'constitutional', subject:'Direito Constitucional', topic:'Remédios constitucionais', statement:'Uma pessoa sofre ameaça ilegal de prisão. Qual remédio constitucional protege diretamente sua liberdade de locomoção?', options:['Habeas data','Mandado de injunção','Ação popular','Mandado de segurança coletivo','Habeas corpus'], answer:4, explanation:'O habeas corpus protege a liberdade de locomoção contra violência ou coação ilegal, efetiva ou ameaçada. Habeas data trata de informações pessoais; mandado de segurança protege direito líquido e certo não amparado por HC ou HD.', basis:'CF, art. 5º, LXVIII a LXXII', source:SOURCES.cf },
  { id:'adm-delegacao', discipline:'administrative', subject:'Direito Administrativo', topic:'Competência administrativa', statement:'Na Administração Federal, qual matéria a Lei nº 9.784/1999 proíbe delegar?', options:['Edição de atos normativos','Atividade material rotineira, sempre','Toda competência de órgão colegiado','Toda competência para órgão sem subordinação','Qualquer atividade técnica'], answer:0, explanation:'Não se delegam edição de atos normativos, decisão de recursos administrativos e matérias de competência exclusiva. Outras competências podem ser parcialmente delegadas, inclusive sem subordinação hierárquica, se presentes os requisitos legais.', basis:'Lei nº 9.784/1999, arts. 12 e 13', source:SOURCES.processo },
  { id:'adm-autotutela', discipline:'administrative', subject:'Direito Administrativo', topic:'Anulação e revogação', statement:'Um ato válido deixou de ser conveniente à Administração. Respeitados os limites legais, qual providência corresponde a esse motivo?', options:['Anulação por ilegalidade','Cassação automática','Convalidação de ilegalidade','Revogação por conveniência ou oportunidade','Declaração de inexistência'], answer:3, explanation:'Revogação é retirada de ato válido por mérito administrativo. Anulação enfrenta ilegalidade. A decisão precisa respeitar direitos adquiridos e demais limites, e ser motivada nas hipóteses legais.', basis:'Lei nº 9.784/1999, arts. 50 e 53', source:SOURCES.processo, rubric:['Reconhecer validade do ato','Distinguir ilegalidade de mérito','Concluir pela revogação e indicar limites'] },
  { id:'adm-convalidacao', discipline:'administrative', subject:'Direito Administrativo', topic:'Convalidação', statement:'Foi identificado defeito sanável em ato administrativo federal. Qual condição legal permite convalidá-lo?', options:['Prejuízo a terceiros, se pequeno','Defeito em qualquer competência exclusiva','Ausência de lesão ao interesse público e de prejuízo a terceiros','Dispensa de motivação em todo caso','Concordância do agente substitui a lei'], answer:2, explanation:'O art. 55 permite convalidar defeitos sanáveis quando não houver lesão ao interesse público nem prejuízo a terceiros. Não confunda a possibilidade de saneamento com autorização para corrigir qualquer vício.', basis:'Lei nº 9.784/1999, art. 55', source:SOURCES.processo },
  { id:'ser-posse', discipline:'trt-legislation', subject:'Regimento/Legislação TRT', topic:'Posse e exercício', statement:'Servidor federal foi nomeado. Sem impedimento legal especial, quais são os prazos de posse e exercício, respectivamente?', options:['15 dias da publicação e 30 dias da posse','30 dias da publicação e 15 dias da posse','30 dias da posse e 30 dias do exercício','Cinco e dez dias','60 e 90 dias'], answer:1, explanation:'A posse ocorre em 30 dias da publicação do ato de provimento. O exercício ocorre em 15 dias da posse. São marcos iniciais diferentes; a investidura ocorre com a posse.', basis:'Lei nº 8.112/1990, arts. 7º, 13, § 1º, e 15, § 1º', source:SOURCES.servidor, rubric:['Distinguir posse e exercício','Indicar 30 dias a partir da publicação','Indicar 15 dias a partir da posse'] },
  { id:'ser-remocao', discipline:'trt-legislation', subject:'Regimento/Legislação TRT', topic:'Remoção e redistribuição', statement:'Ocorre deslocamento do servidor no mesmo quadro, com mudança de sede. Qual instituto corresponde à descrição?', options:['Redistribuição, necessariamente','Reintegração','Recondução','Readaptação','Remoção'], answer:4, explanation:'Remoção desloca o servidor no âmbito do mesmo quadro, com ou sem mudança de sede. Redistribuição desloca o cargo efetivo para outro órgão ou entidade do mesmo Poder, nas condições legais.', basis:'Lei nº 8.112/1990, arts. 36 e 37', source:SOURCES.servidor },
  { id:'ser-penal', discipline:'trt-legislation', subject:'Regimento/Legislação TRT', topic:'Responsabilidades', statement:'Servidor é absolvido criminalmente porque ficou provado que não foi autor do fato. Qual efeito prevê a Lei nº 8.112/1990?', options:['Nenhum efeito administrativo em qualquer hipótese','Demissão obrigatória','Afastamento da responsabilidade administrativa por esse fato','Responsabilidade administrativa automática','Conversão obrigatória em advertência'], answer:2, explanation:'A absolvição criminal que nega a existência do fato ou a autoria afasta a responsabilidade administrativa. Não generalize para toda absolvição: insuficiência de provas, por exemplo, não equivale a negar a autoria.', basis:'Lei nº 8.112/1990, arts. 125 e 126', source:SOURCES.servidor },
  { id:'cpc-prazo', discipline:'civil-procedure', subject:'Direito Processual Civil', topic:'Prazos', statement:'No CPC, um prazo processual foi fixado em 15 dias. Sem regra especial, como se faz a contagem?', options:['Em dias úteis','Em dias corridos, sempre','Somente em dias de audiência','Em meses','Em dias úteis, inclusive qualquer prazo de direito material'], answer:0, explanation:'O art. 219 manda computar somente dias úteis nos prazos processuais em dias. Seu parágrafo único limita a regra aos prazos processuais; não se aplica indistintamente a prazos materiais.', basis:'CPC, art. 219', source:SOURCES.cpc },
  { id:'cpc-emenda', discipline:'civil-procedure', subject:'Direito Processual Civil', topic:'Petição inicial', statement:'Em uma ação civil, a petição inicial apresenta defeito sanável. Antes de indeferi-la, qual providência o juiz deve adotar segundo o CPC?', options:['Extinguir imediatamente','Conceder oito dias sem indicar o defeito','Conceder cinco dias','Determinar emenda em 15 dias, indicando precisamente a correção necessária','Remeter ao STF'], answer:3, explanation:'O juiz deve indicar com precisão o que precisa ser corrigido ou completado e conceder 15 dias. O indeferimento por descumprimento vem depois da oportunidade de emenda.', basis:'CPC, art. 321', source:SOURCES.cpc, rubric:['Reconhecer defeito sanável','Conceder oportunidade de emenda','Indicar prazo de 15 dias e precisão da determinação'] },
  { id:'cpc-evidencia', discipline:'civil-procedure', subject:'Direito Processual Civil', topic:'Tutela provisória', statement:'A parte pretende tutela da evidência. É indispensável demonstrar perigo de dano?', options:['Sim, em qualquer hipótese','Não; é necessário enquadramento em uma das hipóteses do art. 311','Não; basta afirmar que tem razão','Sim, além de sentença definitiva','Somente se o juiz desejar'], answer:1, explanation:'Tutela da evidência independe de perigo de dano ou risco ao resultado útil, mas exige hipótese legal. Não é concessão automática: a evidência precisa atender ao art. 311.', basis:'CPC, art. 311', source:SOURCES.cpc },
  { id:'lgpd-sensivel', discipline:'lgpd-digital', subject:'LGPD e Direito Digital', topic:'Dados pessoais sensíveis', statement:'Qual informação é classificada pela LGPD como dado pessoal sensível?', options:['CEP genérico de uma cidade','Preço de um produto','Dado de saúde vinculado a pessoa natural','Nome de uma pessoa jurídica','Quantidade de mesas de um prédio'], answer:2, explanation:'Dados referentes à saúde vinculados a pessoa natural são sensíveis. A classificação exige atenção ao objeto e à vinculação, e não apenas ao fato de uma informação parecer reservada.', basis:'LGPD, art. 5º, II', source:SOURCES.lgpd },
  { id:'lgpd-base', discipline:'lgpd-digital', subject:'LGPD e Direito Digital', topic:'Bases legais', statement:'Um órgão trata dados pessoais não sensíveis para cumprir obrigação legal. O consentimento é sempre obrigatório?', options:['Sim, sem exceções','Sim, se os dados forem digitais','Sim, substituindo a obrigação legal','Não; cumprimento de obrigação legal ou regulatória é base própria, observados os demais requisitos','Não existe proteção no setor público'], answer:3, explanation:'Consentimento é uma das bases, não a única. O art. 7º, II, admite cumprimento de obrigação legal ou regulatória. Isso não dispensa finalidade, necessidade, segurança e as regras aplicáveis ao Poder Público.', basis:'LGPD, arts. 6º, 7º, II, e 23', source:SOURCES.lgpd, rubric:['Identificar a base legal','Afastar obrigatoriedade universal de consentimento','Manter os demais princípios e requisitos'] },
  { id:'lgpd-minimo', discipline:'lgpd-digital', subject:'LGPD e Direito Digital', topic:'Princípios', statement:'Um formulário coleta dados que não são necessários à sua finalidade. Qual princípio é diretamente contrariado?', options:['Necessidade','Publicidade irrestrita','Livre cobrança','Hierarquia','Irretroatividade'], answer:0, explanation:'Necessidade limita o tratamento ao mínimo necessário: dados pertinentes, proporcionais e não excessivos. Uma finalidade legítima não autoriza coleta ilimitada.', basis:'LGPD, art. 6º, III', source:SOURCES.lgpd },
  { id:'pt-inferencia', discipline:'portuguese', subject:'Português', topic:'Interpretação e inferência', statement:'Leia: “Embora o atendimento tenha sido ampliado, as filas permaneceram longas.” O texto permite concluir que:', options:['A ampliação eliminou as filas','As filas só começaram depois da ampliação','Nenhuma pessoa foi atendida','O atendimento piorou necessariamente','A ampliação não bastou para eliminar as filas longas'], answer:4, explanation:'“Embora” introduz concessão: o atendimento foi ampliado, mas persistiram filas longas. Não se pode inferir piora, ausência de atendimento ou causalidade apenas com os dados fornecidos.', basis:'Concessão e inferência textual; enunciado autoral', source:'' },
  { id:'pt-concordancia', discipline:'portuguese', subject:'Português', topic:'Concordância verbal', statement:'Qual frase atende à norma-padrão?', options:['Houveram muitas reclamações','Haviam três processos pendentes','Houve muitas reclamações','Fazem dois anos que estudo','Existia muitos processos'], answer:2, explanation:'“Haver”, com sentido de existir, é impessoal e fica no singular: houve/havia reclamações. “Fazer” indicando tempo também é impessoal. Já “existir” concorda com o sujeito: existiam muitos processos.', basis:'Concordância de verbos impessoais; exercício autoral', source:'' },
  { id:'pt-virgula', discipline:'portuguese', subject:'Português', topic:'Pontuação', statement:'Qual frase emprega corretamente a vírgula?', options:['Os servidores do tribunal, revisaram os documentos.','Os servidores, após a reunião, revisaram os documentos.','Os servidores revisaram, os documentos.','A decisão, foi publicada ontem.','O tribunal recebeu, três recursos.'], answer:1, explanation:'A expressão intercalada “após a reunião” pode ser isolada por duas vírgulas. As demais alternativas separam sujeito e verbo ou verbo e complemento sem justificativa.', basis:'Intercalação e termos essenciais; exercício autoral', source:'' },
  { id:'rlm-percentual', discipline:'math-logic', subject:'Matemática + RLM', topic:'Porcentagem', statement:'Um valor de R$ 100 sofre dois aumentos sucessivos de 10%. Qual é o valor final?', options:['R$ 110','R$ 120','R$ 121','R$ 122','R$ 200'], answer:2, explanation:'100 × 1,10 × 1,10 = 121. O segundo aumento incide sobre 110, não sobre 100. A taxa acumulada é 21%, e não 20%.', basis:'Fatores percentuais sucessivos; exercício autoral', source:'' },
  { id:'rlm-negacao', discipline:'math-logic', subject:'Matemática + RLM', topic:'Lógica proposicional', statement:'Qual é a negação de “Ana estuda e Bruno revisa”?', options:['Ana não estuda e Bruno não revisa','Ana estuda ou Bruno revisa','Se Ana estuda, Bruno não revisa','Ana não estuda ou Bruno não revisa','Ana estuda e Bruno não revisa'], answer:3, explanation:'Pela lei de De Morgan, ¬(p ∧ q) equivale a ¬p ∨ ¬q. Trocam-se “e” por “ou” e negam-se as duas proposições. “Ou” é inclusivo.', basis:'Lei de De Morgan; exercício autoral', source:'' },
  { id:'rlm-contrapositiva', discipline:'math-logic', subject:'Matemática + RLM', topic:'Condicional', statement:'Qual proposição é equivalente a “Se estudo, então aprendo”?', options:['Se aprendo, então estudo','Se não estudo, então não aprendo','Estudo se e somente se aprendo','Estudo e aprendo','Se não aprendo, então não estudo'], answer:4, explanation:'A contrapositiva ¬q → ¬p é equivalente a p → q. A recíproca (q → p) e a inversa (¬p → ¬q) não são equivalentes em geral.', basis:'Equivalência da condicional; exercício autoral', source:'' },
];

export function scorePractice(answers: Map<string, number>, bank = PRACTICE_BANK) {
  const attempted = bank.filter((question) => answers.has(question.id));
  const correct = attempted.filter((question) => answers.get(question.id) === question.answer).length;
  return { total: attempted.length, correct, accuracy: attempted.length ? Math.round(100 * correct / attempted.length) : null };
}
