const trt4Decks = [
  {
    id: "trt4-overview",
    title: "Comece aqui · TRT4 AJAJ",
    cards: [
      { front: "Qual é o cargo-alvo deste plano de estudos?", back: "Analista Judiciário - Área Judiciária do Tribunal Regional do Trabalho da 4ª Região.", example: "Fonte: Edital Verticalizado TRT4 AJAJ, versão 2.0, p. 1." },
      { front: "Este material já corresponde ao novo edital oficial de 2026?", back: "Não. O próprio documento se identifica como pré-edital e usa a FCC e o edital de 2022 como base histórica.", example: "Atenção: banca, formato, pesos e conteúdo do novo certame ainda precisam de confirmação oficial." },
      { front: "Como foi estruturada a prova objetiva do TRT4 AJAJ em 2022?", back: "30 questões de conhecimentos gerais com peso 1 e 30 questões específicas com peso 2.", example: "Base histórica: prova de 10/07/2022. O novo edital poderá alterar a estrutura." },
      { front: "Quais disciplinas tiveram maior incidência ponderada na prova-base de 2022?", back: "Processo do Trabalho (17,8%), Português e Administrativo (16,7% cada) e Direito do Trabalho (15,6%).", example: "Fonte: dashboard do edital verticalizado, p. 2." },
      { front: "Qual ciclo de revisões é proposto pelo material?", back: "Revisões em 24 horas, 7 dias e 30 dias, usando perguntas, artigos marcados e questões erradas.", example: "Fonte: edital verticalizado, pp. 17-18." },
      { front: "Qual é a regra de segurança quando sair o novo edital?", back: "O novo edital oficial prevalece. Pesos, mínimos, disciplinas e conteúdo devem ser conferidos e recalculados.", example: "Até lá, o leitor trabalha o núcleo estrutural indicado no pré-edital." },
    ],
  },
  {
    id: "labor-procedure",
    title: "Processo do Trabalho · 17,8%",
    cards: [
      { front: "Quais dispositivos orientam o estudo da organização e competência da Justiça do Trabalho?", back: "Constituição Federal, arts. 111 a 116, e CLT, arts. 643 a 735.", example: "Prioridade A · foco em competência material, funcional, Varas, TRTs e TST." },
      { front: "Quando o CPC pode ser aplicado ao processo do trabalho?", back: "Quando houver lacuna e compatibilidade com o processo trabalhista, observadas a CLT, o CPC e a regulamentação do TST.", example: "Roteiro: CLT, arts. 763 a 769 e 889; CPC, art. 15; IN TST 39/2016." },
      { front: "Quais artigos concentram audiência, conciliação, notificação, arquivamento e revelia?", back: "CLT, arts. 813 a 817 e 843 a 852, com o CPC aplicado quando compatível.", example: "Prioridade A · comparar comparecimento, preposto, ausência e efeitos." },
      { front: "Onde estudar provas e ônus da prova no processo trabalhista?", back: "CLT, art. 818, CPC, arts. 369 a 484, e súmulas/orientações jurisprudenciais pertinentes do TST.", example: "Prioridade A · prova documental, testemunhal, pericial e distribuição do ônus." },
      { front: "Quais artigos regem o procedimento sumaríssimo trabalhista?", back: "CLT, arts. 852-A a 852-I.", example: "Prioridade A · cabimento, exclusões, citação, prova e sentença." },
      { front: "Qual é o núcleo de lei seca para liquidação e execução trabalhista?", back: "CLT, arts. 876 a 892, com aplicação subsidiária dos dispositivos compatíveis do CPC.", example: "Prioridade A · liquidação, títulos, garantia, penhora, defesa e expropriação." },
      { front: "Onde se concentra o sistema recursal trabalhista?", back: "CLT, arts. 893 a 902, além dos dispositivos especiais e da jurisprudência vigente do TST.", example: "Estude cabimento, prazo, preparo, efeitos e pressupostos." },
      { front: "Qual era a incidência histórica de Processo do Trabalho na prova-base?", back: "Oito questões específicas, equivalentes a 17,8% da pontuação objetiva ponderada.", example: "Maior incidência específica da prova de 2022." },
    ],
  },
  {
    id: "portuguese",
    title: "Português · 16,7%",
    cards: [
      { front: "Qual é o primeiro passo diante de uma questão de interpretação da FCC?", back: "Separar o que está expresso do que é inferência, tese, pressuposto ou opinião, sempre retornando ao texto-base.", example: "Prioridade A · a FCC costuma integrar interpretação e gramática." },
      { front: "O que deve ser preservado em uma reescrita correta?", back: "Correção gramatical, sentido original, relações lógico-semânticas, coesão e adequação ao contexto.", example: "A troca de conectivo, tempo verbal ou regência pode alterar o sentido." },
      { front: "Quando ocorre crase antes de uma palavra feminina?", back: "Quando a preposição “a”, exigida pelo termo anterior, se funde com o artigo feminino “a” ou “as”.", example: "Prioridade A · relacione crase e regência; observe casos facultativos e proibidos." },
      { front: "A vírgula pode separar sujeito e predicado?", back: "Em regra, não. A separação só se justifica quando existe elemento intercalado ou outra estrutura que exija pontuação.", example: "Prioridade A · avalie sempre o efeito sintático e semântico." },
      { front: "Qual é a diferença entre coesão e coerência?", back: "Coesão articula linguisticamente as partes do texto; coerência mantém a unidade de sentido e a compatibilidade lógica das ideias.", example: "Prioridade A · conectores, retomadas, paralelismo e progressão." },
      { front: "O que a FCC costuma cobrar em concordância e regência?", back: "Casos contextualizados, mudança de sentido, identificação de complementos e reescritas completas — não apenas regras isoladas.", example: "Prioridade A · teste a frase inteira depois da alteração." },
      { front: "Qual foi a incidência de Português na prova-base de 2022?", back: "Quinze questões gerais, equivalentes a 16,7% da pontuação objetiva ponderada.", example: "Maior quantidade bruta de questões entre as disciplinas." },
    ],
  },
  {
    id: "administrative",
    title: "Direito Administrativo · 16,7%",
    cards: [
      { front: "Quais princípios expressos regem a Administração Pública?", back: "Legalidade, impessoalidade, moralidade, publicidade e eficiência — LIMPE.", example: "CF, art. 37, caput; Lei 9.784/1999, art. 2º." },
      { front: "Quais poderes administrativos devem ser comparados para a prova?", back: "Hierárquico, disciplinar, regulamentar e de polícia, além das formas de abuso: excesso de poder e desvio de finalidade.", example: "Prioridade A · CF, art. 84, IV; CTN, art. 78; Lei 9.784/1999." },
      { front: "Qual é a diferença central entre anulação e revogação?", back: "A anulação combate ilegalidade; a revogação retira ato válido por conveniência e oportunidade, respeitados seus limites.", example: "Lei 9.784/1999, arts. 53 a 55; revisar também convalidação." },
      { front: "Quais entidades integram a Administração indireta federal?", back: "Autarquias, empresas públicas, sociedades de economia mista e fundações públicas.", example: "DL 200/1967, arts. 4º e 5º; CF, art. 37, XIX e XX." },
      { front: "Qual é a matriz legal indicada para servidores públicos federais?", back: "Constituição Federal, arts. 37 a 41, e Lei 8.112/1990, especialmente os blocos de ingresso, vantagens, deveres, sanções e PAD.", example: "Prioridade A · edital verticalizado, pp. 6 e 14." },
      { front: "Quais pontos formam o núcleo do processo administrativo federal?", back: "Competência, impedimento, forma, motivação, recursos, anulação e autotutela.", example: "Lei 9.784/1999, arts. 1º a 69." },
      { front: "Quais blocos da Lei 14.133/2021 recebem prioridade?", back: "Princípios, agentes, fases e modalidades; contratação direta; contratos; prerrogativas; extinção e sanções.", example: "Artigos indicados: 1º-11, 17-33, 62-75, 89-95 e 104-163." },
      { front: "Por que Administrativo aparece com incidência elevada?", back: "Na prova-base foram classificadas dez questões: cinco no bloco geral e cinco no específico.", example: "Incidência ponderada histórica: 16,7%." },
    ],
  },
  {
    id: "labor-law",
    title: "Direito do Trabalho · 15,6%",
    cards: [
      { front: "Quais artigos da CLT formam o núcleo da relação de emprego?", back: "CLT, arts. 2º e 3º, complementados pelos arts. 6º, 10 e demais dispositivos indicados para contrato e responsabilidade.", example: "Prioridade A · empregador, empregado, subordinação e alteridade." },
      { front: "Quais elementos caracterizam, em regra, a relação de emprego?", back: "Prestação por pessoa física, pessoalidade, não eventualidade, onerosidade e subordinação, com os riscos da atividade assumidos pelo empregador.", example: "CLT, arts. 2º e 3º." },
      { front: "Onde estudar jornada, intervalos e teletrabalho?", back: "CLT, arts. 57 a 75, além do art. 7º da Constituição e da jurisprudência vigente.", example: "Prioridade A · duração, compensação, descanso e regimes especiais." },
      { front: "Qual é o núcleo legal de remuneração e salário?", back: "CLT, arts. 457 a 467, com os dispositivos constitucionais e precedentes pertinentes.", example: "Prioridade A · parcelas salariais, gorjetas, equiparação e descontos." },
      { front: "Quais dispositivos concentram alteração e extinção do contrato?", back: "CLT, arts. 468 a 486, sem prejuízo dos artigos especiais sobre estabilidade e proteção.", example: "Prioridade A · alteração lesiva, justa causa, rescisão indireta e verbas." },
      { front: "Onde está o núcleo de negociação coletiva?", back: "Constituição Federal, art. 7º, XXVI, e CLT, arts. 611 a 625, com destaque para 611-A e 611-B.", example: "Prioridade A · acordo, convenção e limites do negociado." },
      { front: "Quais temas devem ser cruzados com jurisprudência do TST e STF?", back: "Terceirização, jornada, justiça gratuita, negociação coletiva, responsabilidade e atualização de créditos, entre outros pontos do roteiro.", example: "Antes de memorizar, conferir redação e vigência do precedente." },
      { front: "Qual foi a incidência histórica de Direito do Trabalho?", back: "Sete questões específicas, equivalentes a 15,6% da pontuação objetiva ponderada.", example: "Base: prova TRT4 AJAJ de 2022." },
    ],
  },
  {
    id: "constitutional",
    title: "Direito Constitucional · 11,1%",
    cards: [
      { front: "Quais temas formam o núcleo de princípios fundamentais?", back: "Fundamentos, objetivos fundamentais, princípios das relações internacionais e estrutura do Estado Democrático de Direito.", example: "Constituição Federal, arts. 1º a 4º." },
      { front: "Qual é o foco do controle difuso de constitucionalidade?", back: "Reserva de plenário, efeitos da decisão, atuação do Senado e recurso extraordinário.", example: "CF, arts. 52, X; 97; 102, III; CPC, arts. 948-950; SV 10." },
      { front: "O que deve ser comparado entre ADI, ADC e ADPF?", back: "Legitimidade, objeto, subsidiariedade quando aplicável, cautelar, efeitos e modulação.", example: "CF, arts. 102 e 103; Leis 9.868/1999 e 9.882/1999." },
      { front: "As normas definidoras de direitos e garantias fundamentais têm que tipo de aplicação?", back: "Aplicação imediata.", example: "Constituição Federal, art. 5º, § 1º." },
      { front: "Quais artigos concentram Administração Pública e servidores?", back: "Constituição Federal, arts. 37 a 41.", example: "Prioridade A · concurso, acumulação, teto, estabilidade e responsabilidade." },
      { front: "Quais artigos estruturam a Justiça do Trabalho?", back: "Constituição Federal, arts. 111 a 116, especialmente 111-A, 114 e 115.", example: "Prioridade A · organização e competência material." },
      { front: "Qual foi a incidência histórica de Constitucional?", back: "Cinco questões específicas, equivalentes a 11,1% da pontuação objetiva ponderada.", example: "Base: prova TRT4 AJAJ de 2022." },
    ],
  },
  {
    id: "civil-procedure",
    title: "Processo Civil · 11,1%",
    cards: [
      { front: "Quais artigos do CPC tratam das normas fundamentais e da aplicação?", back: "CPC, arts. 1º a 15.", example: "Prioridade A · cooperação, contraditório, boa-fé e aplicação temporal." },
      { front: "Onde se concentra o estudo da competência no CPC?", back: "CPC, arts. 42 a 69.", example: "Prioridade A · competência absoluta e relativa, modificação e conflito." },
      { front: "Quais artigos abrangem sujeitos, litisconsórcio e intervenção de terceiros?", back: "CPC, arts. 70 a 138.", example: "Capacidade, procuradores, assistência, denunciação, chamamento, IDPJ e amicus curiae." },
      { front: "Qual é o núcleo de tutela provisória?", back: "CPC, arts. 294 a 311.", example: "Urgência, evidência, cautelar, antecipada, estabilização e requisitos." },
      { front: "Quais blocos formam o procedimento comum de conhecimento?", back: "Petição inicial, resposta, saneamento, prova, sentença, coisa julgada e cumprimento, principalmente entre os arts. 319 e 538 do CPC.", example: "Prioridade A · acompanhar a sequência procedimental." },
      { front: "Onde está o núcleo da execução civil?", back: "CPC, arts. 771 a 925, com os dispositivos específicos de cada modalidade.", example: "Prioridade A · penhora, expropriação, defesas, suspensão e extinção." },
      { front: "Qual foi a incidência histórica de Processo Civil?", back: "Cinco questões específicas, equivalentes a 11,1% da pontuação objetiva ponderada.", example: "Base: prova TRT4 AJAJ de 2022." },
    ],
  },
  {
    id: "math-logic",
    title: "Matemática + RLM · 5,6%",
    cards: [
      { front: "Qual cuidado vem antes da conta em uma questão da FCC?", back: "Traduzir o enunciado, identificar os dados e a pergunta, modelar a relação e só então calcular.", example: "O material recomenda cronômetro e controle de interpretação." },
      { front: "Um valor de R$ 200 aumenta 15%. Qual é o novo valor?", back: "R$ 230.", example: "200 × 1,15 = 230." },
      { front: "Um produto sofre dois descontos sucessivos de 10%. O desconto total é 20%?", back: "Não. O valor final é 0,9 × 0,9 = 0,81 do original; o desconto total é 19%.", example: "Prioridade A · porcentagens sucessivas não são somadas diretamente." },
      { front: "Como resolver problemas de divisão proporcional?", back: "Somar as partes da razão, encontrar o valor de uma parte e multiplicar pela quantidade atribuída a cada parcela.", example: "Prioridade A · razões, proporções e modelagem." },
      { front: "O que fazer em problemas de relações arbitrárias e dedução?", back: "Montar tabela ou diagrama, registrar restrições e testar apenas conclusões obrigatórias.", example: "Prioridade A · não extrapolar o enunciado." },
      { front: "Qual foi a incidência histórica de Matemática e RLM?", back: "Cinco questões gerais, equivalentes a 5,6% da pontuação objetiva ponderada.", example: "Na classificação do material: três de Matemática e duas de RLM." },
    ],
  },
  {
    id: "trt-legislation",
    title: "Legislação + RI TRT4 · 3,3%",
    cards: [
      { front: "Quais blocos da Lei 8.112/1990 são prioridade A?", back: "Provimento e vacância; vencimento e vantagens; deveres e proibições; penalidades, prescrição e PAD.", example: "Artigos-base: 1º-35, 40-76-A, 116-182." },
      { front: "Quais temas comparar entre remoção, redistribuição e substituição?", back: "Conceito, requisitos, iniciativa, vinculação ou discricionariedade e efeitos funcionais.", example: "Lei 8.112/1990, arts. 36 a 39 · prioridade B." },
      { front: "Qual é o núcleo da Lei de Improbidade no roteiro?", back: "Dolo, tipicidade, sanções, prescrição e acordo de não persecução civil, conforme o regime posterior à Lei 14.230/2021.", example: "Lei 8.429/1992, artigos indicados no edital verticalizado, p. 6." },
      { front: "Quais blocos do Regimento Interno do TRT4 são indicados?", back: "Organização e competências; serviço e processo no Tribunal; comissões e serviços administrativos.", example: "Roteiro: arts. 1º-72, 73-210 e 211-245 da versão vigente." },
      { front: "Qual versão do Regimento deve ser usada?", back: "A versão oficial vigente. O material orienta conferir a atualização até a RA 19/2026.", example: "Não memorize por resumo desatualizado; confirme no portal oficial do TRT4." },
      { front: "Qual norma aparece para sustentabilidade no Poder Judiciário?", back: "Resolução CNJ 400/2021, no texto vigente, incluindo conceitos, PLS, indicadores, contratações e resíduos.", example: "Prioridade B · arts. 1º a 31 e anexos, segundo o roteiro." },
      { front: "Qual foi a incidência histórica de Regimento/legislação do TRT?", back: "Três questões gerais, equivalentes a 3,3% da pontuação objetiva ponderada.", example: "Apesar do percentual, o material classifica Regimento como prioridade A." },
    ],
  },
  {
    id: "lgpd-digital",
    title: "LGPD + Direito Digital · 2,2%",
    cards: [
      { front: "Quais blocos da LGPD são indicados para fundamentos e tratamento?", back: "Arts. 1º a 6º, 7º a 11 e 17 a 22 da Lei 13.709/2018.", example: "Fundamentos, princípios, bases legais, dados sensíveis e direitos do titular." },
      { front: "Qual é a diferença entre dado pessoal e dado pessoal sensível?", back: "Dado pessoal identifica ou torna identificável uma pessoa; dado sensível envolve categorias especialmente protegidas definidas pela LGPD.", example: "Lei 13.709/2018, art. 5º." },
      { front: "O consentimento é a única base legal para tratamento de dados?", back: "Não. A LGPD prevê diversas bases legais; a aplicável depende da finalidade, do contexto e do tipo de dado.", example: "Lei 13.709/2018, arts. 7º e 11." },
      { front: "Quais blocos tratam de Poder Público e segurança na LGPD?", back: "Arts. 23 a 32, 37 a 41 e 46 a 54.", example: "Tratamento público, registros, agentes, segurança e incidentes." },
      { front: "Qual foi a incidência histórica de LGPD e Direito Digital?", back: "Duas questões gerais, equivalentes a 2,2% da pontuação objetiva ponderada.", example: "Prioridade B · manter revisões programadas sem abandonar o tema." },
    ],
  },
  {
    id: "fcc-writing",
    title: "Redação FCC · protocolo",
    cards: [
      { front: "Qual é o primeiro passo ao receber o tema da redação?", back: "Identificar tema, recorte, gênero e tarefa exata do comando.", example: "Protocolo de treino do edital verticalizado, p. 19." },
      { front: "Como formular uma tese eficaz?", back: "Responder ao problema em uma frase clara, específica e defensável, que organize os argumentos seguintes.", example: "Evite tese vaga ou mera repetição do tema." },
      { front: "Qual projeto de texto é sugerido?", back: "Introdução com tese, dois eixos argumentativos desenvolvidos e conclusão coerente com a resposta proposta.", example: "Planeje antes de redigir para controlar progressão e tempo." },
      { front: "O que revisar na norma-padrão?", back: "Concordância, regência, crase, pontuação, pronomes e ortografia, além de clareza e concisão.", example: "Conectores não substituem relação lógica entre as ideias." },
      { front: "Qual frequência de treino é recomendada?", back: "Uma redação por semana na base e duas por semana na reta final, com reescrita das produções abaixo da meta.", example: "O material sugere reescrever redações abaixo de 70 pontos." },
      { front: "Quais eixos temáticos aparecem como treino?", back: "Trabalho e tecnologia, acesso à Justiça, saúde no trabalho, diversidade, sustentabilidade e democracia/informação.", example: "Use os eixos para repertório e prática, sem inventar dados." },
    ],
  },
];
