const trt4Decks = [
  {
    id: "trt4-overview",
    title: "Comece aqui · TRT4 AJAJ",
    topics: [
      "Dashboard de preparação por disciplina",
      "Estrutura, pesos e mínimos eliminatórios",
      "Prioridades A/B/C e núcleo duro",
      "Edital 2022 × atualização 2026",
    ],
    cards: [],
  },
  {
    id: "labor-procedure",
    title: "Direito Processual do Trabalho · 17,8%",
    topics: [
      "Organização e competência da Justiça do Trabalho",
      "Serviços auxiliares e oficiais de justiça",
      "Peritos e honorários periciais",
      "Ministério Público do Trabalho",
      "Princípios; aplicação subsidiária/supletiva do CPC",
      "Prescrição, decadência e prescrição intercorrente",
      "Atos, termos e prazos processuais",
      "Distribuição e valor da causa",
      "Custas, emolumentos, isenções e Fazenda Pública",
      "Partes, procuradores e jus postulandi",
      "Honorários advocatícios",
      "Litisconsórcio, assistência e substituição processual",
      "Nulidades, exceções e conflitos de competência",
      "Responsabilidade por dano processual",
      "Audiência, conciliação, notificação, arquivamento, revelia e confissão",
      "Provas e ônus",
      "Decisão, coisa julgada e eficácia",
      "Reclamação trabalhista e procedimento ordinário",
      "Procedimento sumaríssimo",
      "Inquérito para apuração de falta grave",
      "Ação rescisória e mandado de segurança",
      "Ação civil pública",
      "IDPJ e acordo extrajudicial",
      "Liquidação de sentença",
      "Execução trabalhista - princípios e espécies",
      "Execução contra Fazenda Pública e massa falida",
      "Citação, garantia, penhora e impenhorabilidade",
      "Defesas na execução e expropriação",
      "Recursos trabalhistas",
      "PJe e atos eletrônicos",
      "Reforma Trabalhista",
      "Política de tratamento adequado das disputas",
      "Jurisprudência trabalhista",
      "Pagamento a dependentes e assistência judiciária",
    ],
    cards: [],
  },
  {
    id: "portuguese",
    title: "Português · 16,7%",
    topics: [
      "Compreensão, interpretação, inferência e argumentação",
      "Tipos e gêneros textuais; adequação ao documento",
      "Ortografia e acentuação gráfica",
      "Pontuação",
      "Crase",
      "Pronomes: emprego, tratamento e colocação",
      "Coesão e coerência",
      "Tempos, modos e vozes verbais",
      "Concordância nominal e verbal",
      "Regência nominal e verbal",
      "Morfossintaxe; classes de palavras e termos da oração",
      "Coordenação e subordinação",
      "Figuras de linguagem e discurso direto/indireto/livre",
      "Redação: confronto e reconhecimento de frases",
    ],
    cards: [],
  },
  {
    id: "administrative",
    title: "Direito Administrativo · 16,7%",
    topics: [
      "Princípios da Administração",
      "Poderes administrativos e abuso",
      "Atos administrativos",
      "Organização administrativa",
      "Consórcios e órgãos públicos",
      "Servidores públicos - matriz constitucional",
      "Regime jurídico federal",
      "Processo administrativo",
      "Controle da Administração",
      "Responsabilidade extracontratual do Estado",
      "Improbidade administrativa",
      "Carreiras do Poder Judiciário da União",
      "Licitações e contratos",
      "Serviços públicos e delegação",
      "Bens públicos",
      "Intervenção do Estado na propriedade",
      "Terceiro Setor e entes paraestatais",
    ],
    cards: [],
  },
  {
    id: "labor-law",
    title: "Direito do Trabalho · 15,6%",
    topics: [
      "Princípios e fontes do Direito do Trabalho",
      "Direitos constitucionais dos trabalhadores",
      "Relação de trabalho e relação de emprego",
      "Empregado, empregador e poderes empregatícios",
      "Grupo econômico, sucessão e responsabilidades",
      "CTPS e identificação profissional",
      "Contrato individual de trabalho",
      "Alteração contratual e jus variandi",
      "Suspensão e interrupção",
      "Extinção do contrato e justas causas",
      "Despedida coletiva e culpa recíproca",
      "Aviso prévio",
      "Estabilidades e garantias provisórias",
      "Duração e jornada",
      "Intervalos, descanso semanal e trabalho noturno",
      "Compensação e banco de horas",
      "Salário, remuneração e parcelas",
      "13º salário",
      "Equiparação salarial e desvio de função",
      "Férias",
      "FGTS",
      "Prescrição e decadência",
      "Segurança e medicina; CIPA; EPI",
      "Insalubridade e periculosidade",
      "Categorias com disposições especiais",
      "Proteção à mulher, gestante e menor",
      "Organização sindical e liberdade sindical",
      "Convenções e acordos coletivos",
      "Greve e serviços essenciais",
      "Renúncia e transação",
      "Teletrabalho",
      "Dano moral trabalhista, assédio e discriminação",
      "Acidente do trabalho e responsabilidade civil",
      "Jurisprudência do STF e TST",
    ],
    cards: [],
  },
  {
    id: "constitutional",
    title: "Direito Constitucional · 11,1%",
    topics: [
      "Princípios fundamentais",
      "Aplicabilidade, vigência e eficácia das normas",
      "Controle difuso",
      "ADI e ADC",
      "ADPF",
      "Direitos e deveres individuais e coletivos",
      "Remédios constitucionais",
      "Direitos sociais e dos trabalhadores",
      "Nacionalidade",
      "Direitos políticos e partidos",
      "Organização político-administrativa",
      "Administração Pública e servidores",
      "Poder Executivo",
      "Poder Legislativo e processo legislativo",
      "Poder Judiciário - estrutura geral",
      "STF e STJ",
      "Justiça do Trabalho e CSJT",
      "Funções essenciais à Justiça",
    ],
    cards: [],
  },
  {
    id: "civil-procedure",
    title: "Direito Processual Civil · 11,1%",
    topics: [
      "Normas fundamentais, fontes e aplicação",
      "Jurisdição, ação e limites",
      "Competência",
      "Sujeitos, capacidade, deveres e procuradores",
      "Litisconsórcio e intervenção de terceiros",
      "Juiz e auxiliares",
      "MP, Advocacia Pública, Defensoria e Fazenda Pública",
      "Atos processuais, forma, tempo, lugar e prazos",
      "Comunicação e nulidades",
      "Tutela provisória",
      "Formação, suspensão e extinção",
      "Petição inicial, pedido e improcedência liminar",
      "Audiência, contestação, reconvenção e revelia",
      "Providências preliminares, saneamento e julgamento conforme o estado",
      "Teoria geral da prova e ônus",
      "Provas em espécie",
      "Sentença, remessa necessária e coisa julgada",
      "Liquidação e cumprimento de sentença",
      "Recursos - teoria geral",
      "Agravo e embargos de declaração",
      "Precedentes, repercussão e repetitivos",
      "Execução - normas gerais e espécies",
      "Execução por quantia",
      "Execução contra Fazenda, fazer/não fazer e embargos",
      "Exceção de pré-executividade, remição, suspensão e extinção",
      "Procedimentos especiais",
      "Ações constitucionais e coletivas",
      "Controle de constitucionalidade no processo",
      "IAC, IRDR, conflito, rescisória e reclamação",
    ],
    cards: [],
  },
  {
    id: "math-logic",
    title: "Matemática + RLM · 5,6%",
    topics: [
      "Números inteiros e racionais; operações e expressões",
      "Múltiplos e divisores",
      "Frações",
      "Razões, proporções e divisão proporcional",
      "Regra de três e porcentagem",
      "Relações arbitrárias e dedução",
      "Raciocínio verbal, sequencial, espacial e temporal",
      "Hipóteses e conclusões válidas",
    ],
    cards: [],
  },
  {
    id: "trt-legislation",
    title: "Regimento/Legislação TRT · 3,3%",
    topics: [
      "Lei 8.112/1990 - disposições preliminares; provimento e vacância",
      "Lei 8.112 - remoção, redistribuição e substituição",
      "Lei 8.112 - vencimento, remuneração e vantagens",
      "Lei 8.112 - férias, licenças e afastamentos",
      "Lei 8.112 - deveres, proibições, acumulação e responsabilidades",
      "Lei 8.112 - penalidades, prescrição e PAD",
      "Processo administrativo federal",
      "Improbidade administrativa - regime atual",
      "Nova Lei de Licitações - princípios, agentes, fases e modalidades",
      "Contratação direta, contratos e sanções",
      "Lei Brasileira de Inclusão",
      "Regimento Interno do TRT-4 - organização e competências",
      "Regimento - serviço e processo no Tribunal",
      "Regimento - comissões e serviços administrativos",
      "Sustentabilidade no Poder Judiciário",
    ],
    cards: [],
  },
  {
    id: "lgpd-digital",
    title: "LGPD / Direito Digital · 2,2%",
    topics: [
      "LGPD - fundamentos, tratamento e direitos",
      "LGPD no Poder Público e segurança",
    ],
    cards: [],
  },
  {
    id: "fcc-writing",
    title: "Redação FCC · protocolo",
    topics: [
      "Comando",
      "Tese",
      "Projeto",
      "Argumentação",
      "Coesão",
      "Norma-padrão",
      "Fechamento",
      "Treino",
    ],
    cards: [],
  },
  {
    id: "labor-justice-organs",
    title: "Justiça do Trabalho · CF/88 e CLT",
    sourceNote: "Fonte oficial: Constituição Federal e CLT — Planalto. Texto vigente consultado em 17/08/2026.",
    topics: [],
    cards: [],
  },
];
