import { useEffect, useMemo, useState } from 'react';
import type { User } from '@supabase/supabase-js';
import { getSupabaseClient } from '../lib/supabase-client';
import { useStudyWorkspace } from '../study/useStudyWorkspace';
import {
  createQuestion,
  importQuestions,
  listManagedQuestions,
  markQuestionDuplicates,
  parseQuestionJson,
  restoreQuestion,
  softDeleteQuestion,
  updateQuestion,
  type ManagedQuestion,
  type QuestionDraft,
  type QuestionImportCandidate,
} from './question-manager-repository';
import './question-manager.css';

type FormState = QuestionDraft & { id?: string; alternativesText: string; tagsText: string };
const EMPTY: FormState = { statement:'', subjectId:'', topicId:'', board:'FCC', exam:'', examYear:null, alternatives:[], alternativesText:'', correctAnswer:'', explanation:'', legalBasis:'', source:'', sourceUrl:'', tags:[], tagsText:'' };

export function QuestionManagerLauncher({ user }: { user: User }) {
  const workspace = useStudyWorkspace(user);
  const [open,setOpen]=useState(false); const [rows,setRows]=useState<ManagedQuestion[]>([]); const [loading,setLoading]=useState(false);
  const [query,setQuery]=useState(''); const [subjectFilter,setSubjectFilter]=useState('all'); const [trash,setTrash]=useState(false);
  const [editor,setEditor]=useState(false); const [form,setForm]=useState<FormState>(EMPTY); const [message,setMessage]=useState<string|null>(null);
  const [importOpen,setImportOpen]=useState(false); const [importRows,setImportRows]=useState<QuestionImportCandidate[]>([]); const [importStatus,setImportStatus]=useState<string|null>(null);

  async function refresh(){ if(!workspace.profile)return; setLoading(true); try{setRows(await listManagedQuestions(getSupabaseClient(),workspace.profile.id));}finally{setLoading(false);} }
  useEffect(()=>{if(open&&workspace.profile)void refresh();},[open,workspace.profile?.id]);
  const filtered=useMemo(()=>rows.filter(row=>{if(trash?!row.deleted_at:Boolean(row.deleted_at))return false;if(subjectFilter!=='all'&&row.subject_id!==subjectFilter)return false;const h=`${row.statement} ${row.explanation||''} ${row.legal_basis||''} ${row.board||''}`.toLowerCase();return !query||h.includes(query.toLowerCase());}),[rows,trash,subjectFilter,query]);
  const topics=workspace.topics.filter(topic=>!form.subjectId||topic.subject_id===form.subjectId);

  function edit(row?:ManagedQuestion){ if(!row){setForm({...EMPTY,subjectId:workspace.subjects[0]?.id||'',board:workspace.profile?.board||'FCC'});}else{const alternatives=normalizeAlternatives(row.alternatives);setForm({id:row.id,subjectId:row.subject_id||'',topicId:row.topic_id||'',board:row.board||'',exam:row.exam||'',examYear:row.exam_year,statement:row.statement,alternatives,alternativesText:alternatives.map(a=>`${a.key}) ${a.text}`).join('\n'),correctAnswer:row.correct_answer||'',explanation:row.explanation||'',legalBasis:row.legal_basis||'',source:row.source||'',sourceUrl:row.source_url||'',tags:row.tags||[],tagsText:(row.tags||[]).join(', ')});}setMessage(null);setEditor(true);}
  async function save(){if(!workspace.profile||!form.statement.trim())return setMessage('Enunciado é obrigatório.');const draft:QuestionDraft={...form,alternatives:parseAlternatives(form.alternativesText),tags:form.tagsText.split(',').map(v=>v.trim()).filter(Boolean)};try{form.id?await updateQuestion(getSupabaseClient(),form.id,draft):await createQuestion(getSupabaseClient(),user,workspace.profile.id,draft);setEditor(false);await refresh();}catch(cause){setMessage(cause instanceof Error&&cause.message==='question-duplicate'?'Esta questão já está cadastrada.':cause instanceof Error?cause.message:String(cause));}}
  async function remove(id:string){await softDeleteQuestion(getSupabaseClient(),id);await refresh();}
  async function restore(id:string){try{await restoreQuestion(getSupabaseClient(),id);await refresh();}catch(cause){setMessage(cause instanceof Error&&cause.message==='question-duplicate'?'Já existe uma questão igual ativa.':String(cause));}}
  async function readImport(file:File){if(!workspace.profile)return;try{const parsed=parseQuestionJson(await file.text(),{subjectId:workspace.subjects[0]?.id,board:workspace.profile.board||'FCC'});const marked=await markQuestionDuplicates(getSupabaseClient(),workspace.profile.id,parsed);setImportRows(marked);setImportStatus(`${marked.length} questões analisadas · ${marked.filter(r=>r.duplicate).length} duplicadas bloqueadas.`);}catch(cause){setImportStatus(`Falha: ${cause instanceof Error?cause.message:String(cause)}`);}}
  async function confirmImport(){if(!workspace.profile)return;const result=await importQuestions(getSupabaseClient(),user,workspace.profile.id,importRows);setImportStatus(`${result.inserted} incluídas · ${result.duplicates} duplicadas · ${result.failed} falhas.`);await refresh();setImportRows(await markQuestionDuplicates(getSupabaseClient(),workspace.profile.id,importRows));}

  return <>
    <button className="question-manager-launcher" onClick={()=>setOpen(true)}><span>?</span> Gerenciar questões</button>
    {open?<div className="manager-overlay question-overlay"><div className="manager-overlay-bar"><div><strong>Gerenciar questões</strong><small>{workspace.profile?.name||'Trilha Concursos'}</small></div><button onClick={()=>setOpen(false)}>Voltar aos estudos ×</button></div><div className="page-wrap question-manager-page"><div className="page-header"><div><span className="page-eyebrow">BANCO DE QUESTÕES</span><h1>Gerenciar questões</h1><p>Cadastre, importe e vincule questões ao edital e ao caderno de erros.</p></div><div className="manager-header-actions"><button className="secondary-outline" onClick={()=>setImportOpen(true)}>Importar JSON</button><button className="primary-action" onClick={()=>edit()}>+ Nova questão</button></div></div>
      <div className="manager-toolbar question-toolbar"><div className="search-field manager-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar enunciado, banca ou fundamento"/></div><select value={subjectFilter} onChange={e=>setSubjectFilter(e.target.value)}><option value="all">Todas as disciplinas</option>{workspace.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className={trash?'trash-toggle active':'trash-toggle'} onClick={()=>setTrash(v=>!v)}>{trash?'← Questões ativas':'Lixeira'}</button></div>
      {message?<div className="notice error"><span>{message}</span></div>:null}
      {loading?<div className="study-empty">Carregando questões…</div>:!filtered.length?<div className="empty-feature"><div className="empty-icon">?</div><h2>Nenhuma questão neste filtro.</h2><p>Cadastre manualmente ou importe um arquivo JSON.</p></div>:<div className="managed-question-list">{filtered.map(row=>{const subject=workspace.subjects.find(s=>s.id===row.subject_id);return <article key={row.id} className="managed-question"><div className="question-topline">{row.board?<span>{row.board}</span>:null}{row.exam_year?<span>{row.exam_year}</span>:null}{subject?<span>{subject.name}</span>:null}</div><h2>{row.statement}</h2>{row.correct_answer?<p><strong>Gabarito:</strong> {row.correct_answer}</p>:null}{row.legal_basis?<small>Base legal: {row.legal_basis}</small>:null}<footer>{trash?<button onClick={()=>void restore(row.id)}>Restaurar</button>:<><button onClick={()=>edit(row)}>Editar</button><button className="danger-text" onClick={()=>void remove(row.id)}>Excluir</button></>}</footer></article>;})}</div>}
    </div>
    {editor?<div className="modal-backdrop"><div className="modal-card question-editor"><div className="modal-heading"><div><span className="page-eyebrow">{form.id?'EDITAR':'NOVA QUESTÃO'}</span><h2>{form.id?'Editar questão':'Nova questão'}</h2></div><button className="modal-close" onClick={()=>setEditor(false)}>×</button></div><div className="form-grid"><label><span>Disciplina</span><select value={form.subjectId||''} onChange={e=>setForm(c=>({...c,subjectId:e.target.value,topicId:''}))}><option value="">Sem disciplina</option>{workspace.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span>Assunto</span><select value={form.topicId||''} onChange={e=>setForm(c=>({...c,topicId:e.target.value}))}><option value="">Sem assunto</option>{topics.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label><span>Banca</span><input value={form.board||''} onChange={e=>setForm(c=>({...c,board:e.target.value}))}/></label><label><span>Ano</span><input type="number" value={form.examYear||''} onChange={e=>setForm(c=>({...c,examYear:e.target.value?Number(e.target.value):null}))}/></label><label className="full"><span>Prova/Concurso</span><input value={form.exam||''} onChange={e=>setForm(c=>({...c,exam:e.target.value}))}/></label><label className="full"><span>Enunciado *</span><textarea rows={5} value={form.statement} onChange={e=>setForm(c=>({...c,statement:e.target.value}))}/></label><label className="full"><span>Alternativas — uma por linha</span><textarea rows={5} value={form.alternativesText} onChange={e=>setForm(c=>({...c,alternativesText:e.target.value}))} placeholder={'A) alternativa\nB) alternativa\nC) alternativa'}/></label><label><span>Gabarito</span><input value={form.correctAnswer||''} onChange={e=>setForm(c=>({...c,correctAnswer:e.target.value}))}/></label><label><span>Base legal</span><input value={form.legalBasis||''} onChange={e=>setForm(c=>({...c,legalBasis:e.target.value}))}/></label><label className="full"><span>Comentário/Justificativa</span><textarea rows={4} value={form.explanation||''} onChange={e=>setForm(c=>({...c,explanation:e.target.value}))}/></label><label className="full"><span>Tags</span><input value={form.tagsText} onChange={e=>setForm(c=>({...c,tagsText:e.target.value}))}/></label></div>{message?<p className="pilot-error">{message}</p>:null}<div className="modal-actions"><button className="secondary-outline" onClick={()=>setEditor(false)}>Cancelar</button><button className="primary-action" onClick={()=>void save()}>Salvar questão</button></div></div></div>:null}
    {importOpen?<div className="modal-backdrop"><div className="modal-card import-modal"><div className="modal-heading"><div><span className="page-eyebrow">IMPORTAÇÃO</span><h2>Importar questões</h2><p>Duplicadas ficam em vermelho e não são incluídas.</p></div><button className="modal-close" onClick={()=>setImportOpen(false)}>×</button></div><label className="file-drop"><input type="file" accept="application/json,.json" onChange={e=>e.target.files?.[0]&&void readImport(e.target.files[0])}/><strong>Escolher arquivo JSON</strong><span>Array de questões ou objeto com propriedade questions.</span></label>{importStatus?<p className="import-status">{importStatus}</p>:null}{importRows.length?<div className="import-preview">{importRows.slice(0,100).map(row=><div className={`import-row ${row.duplicate?'duplicate':''}`} key={row.row}><span>{row.row}</span><div><strong>{row.statement||'Enunciado vazio'}</strong><small>{row.correctAnswer?`Gabarito: ${row.correctAnswer}`:'Sem gabarito'}</small>{row.duplicateReason?<em>{row.duplicateReason}</em>:null}</div><span>{row.duplicate?'Duplicada':'Nova'}</span></div>)}</div>:null}<div className="modal-actions"><button className="secondary-outline" onClick={()=>setImportOpen(false)}>Fechar</button><button className="primary-action" disabled={!importRows.some(r=>!r.duplicate)} onClick={()=>void confirmImport()}>Importar válidas</button></div></div></div>:null}
    </div>:null}
  </>;
}

function normalizeAlternatives(value:unknown):Array<{key:string;text:string}>{if(Array.isArray(value))return value.map((item,index)=>typeof item==='string'?{key:String.fromCharCode(65+index),text:item}:item&&typeof item==='object'?{key:String((item as any).key||(item as any).label||String.fromCharCode(65+index)),text:String((item as any).text||(item as any).value||'')}:null).filter(Boolean) as Array<{key:string;text:string}>;if(value&&typeof value==='object')return Object.entries(value as Record<string,unknown>).map(([key,text])=>({key,text:String(text)}));return[];}
function parseAlternatives(text:string){return text.split(/\n+/).map(line=>line.trim()).filter(Boolean).map((line,index)=>{const match=line.match(/^([A-Z0-9]+)[).:\-]\s*(.*)$/i);return match?{key:match[1].toUpperCase(),text:match[2]}:{key:String.fromCharCode(65+index),text:line};});}
